version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: devsu
      POSTGRES_PASSWORD: devsu123
      POSTGRES_DB: bancadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    networks:
      - banca-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsu -d bancadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - banca-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clientes-service:
    build: ./clientes-service
    container_name: clientes-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bancadb
      SPRING_DATASOURCE_USERNAME: devsu
      SPRING_DATASOURCE_PASSWORD: devsu123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banca-network

  cuentas-service:
    build: ./cuentas-service
    container_name: cuentas-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bancadb
      SPRING_DATASOURCE_USERNAME: devsu
      SPRING_DATASOURCE_PASSWORD: devsu123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banca-network

networks:
  banca-network:
    driver: bridge

volumes:
  postgres_data:
